CREATE TABLE IF NOT EXISTS crawler_targets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  url TEXT UNIQUE NOT NULL,
  category TEXT DEFAULT 'spotlight',
  subCategory TEXT DEFAULT '최신 동향',
  isActive INTEGER DEFAULT 1,
  lastCrawledAt DATETIME,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
